services:
  db:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_DB: nomnom
      POSTGRES_USER: nomnom
      POSTGRES_PASSWORD: nomnom
      POSTGRES_INITDB_ARGS: "--locale=en_US.UTF-8"
#      nur für Migrationsskript erstellung
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/nomnom
      SPRING_DATASOURCE_USERNAME: nomnom
      SPRING_DATASOURCE_PASSWORD: nomnom
      SPRING_DEVTOOLS_REMOTE_SECRET: "dev"
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["./mvnw", "spring-boot:run"]

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  pgdata:
