CREATE SEQUENCE IF NOT EXISTS allergen_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS app_user_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS shopping_item_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS shopping_list_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE allergen
(
    id   BIGINT NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_allergen PRIMARY KEY (id)
);

CREATE TABLE allergen_ingredient
(
    ingredient_id BIGINT NOT NULL,
    allergen_id   BIGINT NOT NULL,
    CONSTRAINT pk_allergeningredient PRIMARY KEY (ingredient_id, allergen_id)
);

CREATE TABLE app_user
(
    id         BIGINT NOT NULL,
    name       VARCHAR(255),
    email      VARCHAR(255),
    password   VARCHAR(255),
    preference VARCHAR(255),
    CONSTRAINT pk_app_user PRIMARY KEY (id)
);

CREATE TABLE ingredient
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    type VARCHAR(255),
    unit VARCHAR(255),
    CONSTRAINT pk_ingredient PRIMARY KEY (id)
);

CREATE TABLE recipe
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    description     VARCHAR(2000),
    preference_type VARCHAR(255),
    CONSTRAINT pk_recipe PRIMARY KEY (id)
);

CREATE TABLE recipe_ingredient
(
    recipe_id     BIGINT           NOT NULL,
    ingredient_id BIGINT           NOT NULL,
    amount        DOUBLE PRECISION NOT NULL,
    unit          VARCHAR(255),
    CONSTRAINT pk_recipeingredient PRIMARY KEY (recipe_id, ingredient_id)
);

CREATE TABLE shopping_item
(
    id               BIGINT           NOT NULL,
    shopping_list_id BIGINT,
    ingredient_id    BIGINT,
    amount           DOUBLE PRECISION NOT NULL,
    unit             VARCHAR(255),
    added            BOOLEAN          NOT NULL,
    CONSTRAINT pk_shoppingitem PRIMARY KEY (id)
);

CREATE TABLE shopping_list
(
    id      BIGINT NOT NULL,
    user_id BIGINT,
    CONSTRAINT pk_shoppinglist PRIMARY KEY (id)
);

CREATE TABLE user_allergen
(
    user_id     BIGINT NOT NULL,
    allergen_id BIGINT NOT NULL,
    CONSTRAINT pk_userallergen PRIMARY KEY (user_id, allergen_id)
);

CREATE TABLE user_recipe
(
    user_id    BIGINT NOT NULL,
    recipe_id  BIGINT NOT NULL,
    notes      VARCHAR(255),
    evaluation VARCHAR(255),
    CONSTRAINT pk_userrecipe PRIMARY KEY (user_id, recipe_id)
);

ALTER TABLE shopping_list
    ADD CONSTRAINT uc_shoppinglist_user UNIQUE (user_id);

ALTER TABLE allergen_ingredient
    ADD CONSTRAINT FK_ALLERGENINGREDIENT_ON_ALLERGEN FOREIGN KEY (allergen_id) REFERENCES allergen (id);

ALTER TABLE allergen_ingredient
    ADD CONSTRAINT FK_ALLERGENINGREDIENT_ON_INGREDIENT FOREIGN KEY (ingredient_id) REFERENCES ingredient (id);

ALTER TABLE recipe_ingredient
    ADD CONSTRAINT FK_RECIPEINGREDIENT_ON_INGREDIENT FOREIGN KEY (ingredient_id) REFERENCES ingredient (id);

ALTER TABLE recipe_ingredient
    ADD CONSTRAINT FK_RECIPEINGREDIENT_ON_RECIPE FOREIGN KEY (recipe_id) REFERENCES recipe (id);

ALTER TABLE shopping_item
    ADD CONSTRAINT FK_SHOPPINGITEM_ON_INGREDIENT FOREIGN KEY (ingredient_id) REFERENCES ingredient (id);

ALTER TABLE shopping_item
    ADD CONSTRAINT FK_SHOPPINGITEM_ON_SHOPPING_LIST FOREIGN KEY (shopping_list_id) REFERENCES shopping_list (id);

ALTER TABLE shopping_list
    ADD CONSTRAINT FK_SHOPPINGLIST_ON_USER FOREIGN KEY (user_id) REFERENCES app_user (id);

ALTER TABLE user_allergen
    ADD CONSTRAINT FK_USERALLERGEN_ON_ALLERGEN FOREIGN KEY (allergen_id) REFERENCES allergen (id);

ALTER TABLE user_allergen
    ADD CONSTRAINT FK_USERALLERGEN_ON_USER FOREIGN KEY (user_id) REFERENCES app_user (id);

ALTER TABLE user_recipe
    ADD CONSTRAINT FK_USERRECIPE_ON_RECIPE FOREIGN KEY (recipe_id) REFERENCES recipe (id);

ALTER TABLE user_recipe
    ADD CONSTRAINT FK_USERRECIPE_ON_USER FOREIGN KEY (user_id) REFERENCES app_user (id);