name: Java CI with Tests

on:
  push:
    branches:
      - '*'

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout des Repositories
        uses: actions/checkout@v4

      # Schritt 1: Installiere Maven (falls nicht der Wrapper verwendet wird)
      - name: Installiere Maven
        run: sudo apt-get install -y maven

  build:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Tests ausführen (mit Maven)
        run: mvn clean test -q  # Maven direkt verwenden (ohne Wrapper)

  package:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Build JAR
        run: mvn clean package -q
