name: Java CI with Tests

on:
  push:
    branches:
      - '*'  # Führt den Workflow bei jedem Push aus

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Tests
        working-directory: NomNom-WS
        run: mvn clean test -q

      - name: "Optional: Build JAR"
        working-directory: NomNom-WS
        run: mvn clean package -q