name: Java CI with Tests

on:
  push:
    branches:
      - '*'  # Der Workflow wird für alle Pushes in allen Branches ausgeführt

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # Schritt 1: Checkout des Repositories
      - name: Checkout aktueller Stand
        uses: actions/checkout@v4  # Holt den aktuellen Code aus dem Repository

  build:
    runs-on: ubuntu-latest
    needs: setup  # Dieser Job hängt vom 'setup' Job ab

    steps:
      # Schritt 2: Setup Java (JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # 'temurin' ist die unterstützte Distribution

  test:
    runs-on: ubuntu-latest
    needs: build  # Dieser Job hängt vom 'build' Job ab

    steps:
      # Schritt 3: Installiere Abhängigkeiten und führe Tests aus
      - name: Build und Tests ausführen
        run: ./mvnw clean test -q  # Maven Wrapper (mvnw) verwendet, um Tests auszuführen, '-q' unterdrückt detaillierte Logs

  package:
    runs-on: ubuntu-latest
    needs: test  # Dieser Job hängt vom 'test' Job ab

    steps:
      # Schritt 4: Baue das JAR-Paket
      - name: Build JAR
        run: ./mvnw clean package -q  # Baut die Anwendung und gibt nur essentielle Informationen aus
