name: Java CI with Tests

on:
  push:
    branches:
      - '*'  # Der Workflow wird für alle Pushes in allen Branches ausgeführt

jobs:
  # Job 1: Setup und Checkout
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout aktueller Stand
        uses: actions/checkout@v4  # Holt den aktuellen Code aus dem Repository

  # Job 2: Setup Java (JDK 17) und Abhängigkeiten installieren
  setup-java:
    runs-on: ubuntu-latest
    needs: checkout  # Dieser Job wartet darauf, dass der "checkout"-Job erfolgreich abgeschlossen wird
    steps:
      - name: Checkout aktueller Stand
        uses: actions/checkout@v4  # Holt den aktuellen Code aus dem Repository
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # 'temurin' ist die unterstützte Distribution

  # Job 3: Tests ausführen
  test:
    runs-on: ubuntu-latest
    needs: setup-java  # Dieser Job wartet darauf, dass der "setup-java"-Job erfolgreich abgeschlossen wird
    steps:
      - name: Checkout aktueller Stand
        uses: actions/checkout@v4  # Holt den aktuellen Code aus dem Repository
      - name: Build und Tests ausführen
        run: ./mvnw clean test  # Maven Wrapper (mvnw) verwendet, um Tests auszuführen

  # Job 4: Build das JAR-Paket (optional)
  build-jar:
    runs-on: ubuntu-latest
    needs: test  # Dieser Job wartet darauf, dass der "test"-Job erfolgreich abgeschlossen wird
    steps:
      - name: Checkout aktueller Stand
        uses: actions/checkout@v4  # Holt den aktuellen Code aus dem Repository
      - name: Build JAR
        run: ./mvnw clean package  # Baut die Anwendung (optional)
